# Generated by Django 6.1.1 on 2026-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='difficulty',
            field=models.CharField(default='easy', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
