# Generated by Django 6.1.1 on 2026-09-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='categorized_skills',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='category_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='education_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='experience_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='overall_resume_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='project_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='skills_score',
            field=models.FloatField(default=0),
        ),
    ]
