# Generated by Django 6.1.1 on 2026-09-03 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_score', models.FloatField(default=0)),
                ('skill_score', models.FloatField(default=0)),
                ('career_score', models.FloatField(default=0)),
                ('interview_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('candidate_level', models.CharField(default='Needs Improvement', max_length=50)),
                ('recommended_role', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
