# Generated by Django 6.1.1 on 2026-09-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('DEMO', 'Demo Payment')], default='DEMO', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
